import {
  Newspaper,
  Flag,
  Globe,
  Landmark,
  TrendingUp,
  Trophy,
  Clapperboard,
  Cpu,
  GraduationCap,
  HeartPulse,
  Sparkles,
  MessageSquareQuote,
  ShieldAlert,
  Moon,
  Plane,
  Briefcase,
} from "lucide-react";

export const icons = {
  newspaper: Newspaper,
  flag: Flag,
  globe: Globe,
  landmark: Landmark,
  "trending-up": TrendingUp,
  trophy: Trophy,
  clapperboard: Clapperboard,
  cpu: Cpu,
  "graduation-cap": GraduationCap,
  "heart-pulse": HeartPulse,
  sparkles: Sparkles,
  "message-square-quote": MessageSquareQuote,
  "shield-alert": ShieldAlert,
  moon: Moon,
  plane: Plane,
  briefcase: Briefcase,
} as const;
